sudo: false
language: node_js
node_js:
  - "node"
  - "12"
  - "10"
branches:
  only:
  - master
script: |
  - npm i --global eslint
  - ./bin/test.sh install
  - ./bin/test.sh lint
  - ./bin/test.sh test
